version: '3.8'

services:
  postgres:
    image: postgres
    container_name: todolist-postgres
    restart: always
    environment:
      POSTGRES_USER: elysia
      POSTGRES_PASSWORD: elysia123
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
